[features]
seeds = false
[programs.mainnet]
custos = "CUSto3eB2v7ZbzLTtobb1uwhQQur9gWnWtb3vESvrnwz"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "mainnet"
wallet = "/Users/pratik/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
