[features]
seeds = false
[programs.mainnet]
custos = "6vMc3D2WBwzC7sSp5pHzNKQJYQGFydsP59P2iShYmS9Y"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "mainnet"
wallet = "/Users/pratik/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
