[features]
seeds = false
[programs.devnet]
custos = "3xZo42jGt8vx9huwx2CXYWEcnuetDvurTAG9PLwRzcZo"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/pratik/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
